spring:
  application:
    name: kotobase-backend

  datasource:
    url: jdbc:mysql://localhost:3306/kotobasedemo1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 200904
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

jwt:
  secret: "p7D4tHjxjMzFWDj4tny79JZqQTN+E6e3/gKxbEDYuN4="
  expiration: 3600000